import photo from "../assets/image_bannière.webp"
import hydralift from "../assets/ChatGPT-hydralift.webp"
import laser from "../assets/ChatGPT-laser.webp"

const soins = [
  {
    id: 1,
    name: "Epilation laser",
    description:
      "Pour un premier endez-vous :\n- Tarif indiqué à la séance.\n- Nombre de séances nécessaires : 5 à 10 selon la personne, la zone et le type de poil (ne peut être défini à l'avance).\n- Arrêter l'épilation à la cire ou pince à épiler au moins 1 mois avant.\n- Raser la zone à traiter la veille de la séance.\n- Pas d'exposition directe au soleil 15 jours avant et après la séance.",
    photo: laser,
    prestations: [
      {
        id: 1,
        name: "Consultation",
        description:
          "N'hésitez pas à prendre un rendez-vous gratuit afin que je puisse répondre à toutes vos interrogations et/ou vous faire un devis.",
        durée: "30min",
        prix: 0,
      },
      {
        id: 2,
        name: "Zone flash < 20 min",
        description: "Sourcils, moustache, cou, mains, pieds...",
        durée: "15min",
        prix: 40,
      },
      {
        id: 3,
        name: "Contour barbe",
        description: "Cou compris",
        durée: "20min",
        prix: 60,
      },
      {
        id: 4,
        name: "Barbe entière",
        description: "",
        durée: "30min",
        prix: 80,
      },
      {
        id: 5,
        name: "Avant bras",
        description: "",
        durée: "20min",
        prix: 60,
      },
      {
        id: 6,
        name: "Bras complet",
        description: "",
        durée: "30min",
        prix: 100,
      },
      {
        id: 7,
        name: "Aisselles",
        description: "",
        durée: "20min",
        prix: 40,
      },
      {
        id: 8,
        name: "Dos entier",
        description: "Epaules et nuque comprises",
        durée: "40min",
        prix: 150,
      },
      {
        id: 9,
        name: "Torse entier",
        description: "",
        durée: "45min",
        prix: 150,
      },
      {
        id: 10,
        name: "Maillot échancré",
        description: "SIF et ligne du ventre compris",
        durée: "30min",
        prix: 70,
      },
      {
        id: 11,
        name: "Maillot intégral",
        description: "SIF et ligne du ventre compris",
        durée: "30min",
        prix: 90,
      },
      {
        id: 12,
        name: "SIF",
        description: "",
        durée: "20min",
        prix: 30,
      },
      {
        id: 13,
        name: "Fesses",
        description: "",
        durée: "30min",
        prix: 80,
      },
      {
        id: 14,
        name: "Demi-jambes",
        description: "Jusqu'au dessus du genou + pieds compris",
        durée: "30min",
        prix: 130,
      },
      {
        id: 15,
        name: "Jambes entières",
        description: "Pieds compris",
        durée: "45min",
        prix: 200,
      },
      {
        id: 16,
        name: "Autres zones",
        description: "",
        durée: "30min",
        prix: "Sur devis",
      },
      {
        id: 17,
        name: "Maillot échancré + aisselles",
        description: "Ligne du nombril et SIF offerts",
        durée: "30min",
        prix: 100,
      },
      {
        id: 18,
        name: "Maillot intégral + aisselles",
        description: "Ligne du nombril et SIF offerts",
        durée: "30min",
        prix: 110,
      },
      {
        id: 19,
        name: "Aisselles + demi-jambes",
        description: "Pieds et orteils offerts",
        durée: "40min",
        prix: 160,
      },
      {
        id: 20,
        name: "Aisselles + jambes entières",
        description: "Pieds et orteils offerts",
        durée: "45min",
        prix: 230,
      },
      {
        id: 21,
        name: "Maillot échancré + demi-jambes",
        description: "Ligne du nombril, SIF, pieds et orteils offerts",
        durée: "40min",
        prix: 190,
      },
      {
        id: 22,
        name: "Maillot échancré + jambes entières",
        description: "Ligne du nombril, SIF, pieds et orteils offerts",
        durée: "45min",
        prix: 260,
      },
      {
        id: 23,
        name: "Maillot intégral + demi-jambes",
        description: "Ligne du nombril, SIF, pieds et orteils offerts",
        durée: "40min",
        prix: 210,
      },
      {
        id: 24,
        name: "Maillot intégral + jambes entières",
        description: "Ligne du nombril, SIF, pieds et orteils offerts",
        durée: "45min",
        prix: 280,
      },
      {
        id: 25,
        name: "Aisselles + maillot échancré + demi-jambes",
        description: "Ligne du nombril, SIF, pieds et orteils offerts",
        durée: "1h",
        prix: 230,
      },
      {
        id: 26,
        name: "Aisselles + maillot échancré + jambes entières",
        description: "Ligne du nombril, SIF, pieds et orteils offerts",
        durée: "1h",
        prix: 300,
      },
      {
        id: 27,
        name: "Aisselles + maillot intégral + demi-jambes",
        description: "Ligne du nombril, SIF, pieds et orteils offerts",
        durée: "1h",
        prix: 250,
      },
      {
        id: 28,
        name: "Aisselles + maillot intégral + jambes entières",
        description: "Ligne du nombril, SIF, pieds et orteils offerts",
        durée: "1h",
        prix: 320,
      },
    ],
  },
  {
    id: 2,
    name: "HYDRALIFT",
    description:
      "HydraLift est un soin du visage complet qui combine nettoyage en profondeur, exfoliation douce et hydratation intensive. Ce traitement non invasif associe des actifs hautement concentrés et une technologie de stimulation cutanée pour lisser les traits, améliorer l’élasticité de la peau et raviver l’éclat du teint. Idéal pour un effet “bonne mine” immédiat, il laisse la peau plus fraîche, plus ferme et visiblement revitalisée dès la première séance.",
    photo: hydralift,
    prestations: [
      {
        id: 1,
        name: "Consultation",
        description:
          "N'hésitez pas à prendre un rendez-vous gratuit afin que je puisse répondre à toutes vos interrogations et/ou vous faire un devis.",
        durée: "30min",
        prix: 0,
      },
      {
        id: 2,
        name: "HYDRALIFT Premium",
        description:
          "Soins du visage profond et complet.<br>Convient à tout type de peau.<br>Nettoyage en profondeur (réoxygénation de la peau), extraction sous vide, infusion produit (anti imperfections, anti rides et contre les taches), micro-ondes (stimule les muscles faciaux), radio fréquence/ultrason (booste la production de collagène et circulation sanguine), jetpeel, marteau froid (resserre les pores), led lumineuse.<br>La peau est réhydratée et nettoyée en profondeur.<br>Effet immédiat sur plusieurs semaines.",
        durée: "1h 30min",
        prix: 130,
      },
      {
        id: 3,
        name: "HYDRALIFT anti imperfections",
        description:
          "Soin profond de la peau.<br>Pour les peaux à tendance acnéique, pores dilatés et points noirs.<br>Nettoyage en profondeur (réoxygénation de la peau), vapeur, extraction sous vide et manuelle, infusion produit (anti imperfections), marteau froid (resserre les pores), masque anti imperfections et led lumineuse.<br>La peau est réhydratée et nettoyée en profondeur.<br>Effet immédiat sur plusieurs semaines.",
        durée: "1h",
        prix: 95,
      },
      {
        id: 4,
        name: "HYDRALIFT anti âge",
        description:
          "Soin du visage profond.<br>Convient aux peaux matures.<br>Nettoyage en profondeur (réoxygénation de la peau), infusion produit (anti rides), micro-ondes (stimule les muscles faciaux), radio fréquence/ultrason (booste la production de collagène et circulation sanguine), marteau froid (resserre les pores), led lumineuse.<br>La peau est réhydratée et nettoyée en profondeur.<br>Effet immédiat sur plusieurs semaines.",
        durée: "30 min",
        prix: 80,
      },
    ],
  },
  {
    id: 3,
    name: "Peeling aux algues ZENA",
    description:
      "Un soin naturel pour révéler une peau lisse, lumineuse et rajeunie.\n\nBienfaits :\n- Teint plus lumineux\n- Réduit l'acnée\n- Limite la production de sébum\n- Réduit les pores dilatés\n- Estompe les taches brunes\n- Gomme les cicatrices\n- Lisse les rides et ridules\n- Estompe les vergétures\n- Lutte contre le relâchement cutané.",
    photo: photo,
    prestations: [
      {
        id: 1,
        name: "Consultation",
        description:
          "N'hésitez pas à prendre un rendez-vous gratuit afin que je puisse répondre à toutes vos interrogations et/ou vous faire un devis.",
        durée: "30min",
        prix: 0,
      },
      {
        id: 2,
        name: "Visage (sans booster)",
        description: "",
        durée: "1h",
        prix: 90,
      },
      {
        id: 3,
        name: "Décolleté (sans booster)",
        description: "",
        durée: "1h",
        prix: 95,
      },
      {
        id: 4,
        name: "Aisselles (sans booster)",
        description: "",
        durée: "1h",
        prix: 80,
      },
      {
        id: 5,
        name: "Bras (sans booster)",
        description: "",
        durée: "1h",
        prix: 100,
      },
      {
        id: 6,
        name: "Dos (sans booster)",
        description: "",
        durée: "1h",
        prix: 120,
      },
      {
        id: 7,
        name: "Fesses (sans booster)",
        description: "",
        durée: "1h",
        prix: 110,
      },
      {
        id: 8,
        name: "Cuisses (sans booster)",
        description: "",
        durée: "1h",
        prix: "de 100 à 130 €",
      },
      {
        id: 9,
        name: "Ventre (sans booster)",
        description: "",
        durée: "1h",
        prix: "de 100 à 120 €",
      },
      {
        id: 10,
        name: "Autres zones",
        description: "",
        durée: "1h",
        prix: "Sur devis",
      },
    ],
  },
  {
    id: 4,
    name: "CRYOLIPOLYSE",
    description:
      "Technologie d'amincissement par le froid.\nPermet d'éliminer les amas graisseux localisés.\nZones traitées : double menton, ventre, poignée d'amour, bras, cuisse, culotte de cheval, dos.\nEn général, il faut compter 3 séances par zones.\nPlusieurs zones peuvent être traiter en même temps si elles sont sur la même face du corps.\nPerte de centimètres assurée !\nCONSULTATION OBLIGATOIRE AVANT REALISATION DE LA SEANCE.",
    photo: photo,
    prestations: [
      {
        id: 1,
        name: "Consultation",
        description:
          "Prenez obligatoirement un rendez-vous gratuit afin que je puisse répondre à toutes vos interrogations et/ou vous faire un devis.",
        durée: "30min",
        prix: 0,
      },
      {
        id: 2,
        name: "Cryolipolyse 1 zone",
        description: "",
        durée: "1h30",
        prix: 180,
      },
      {
        id: 3,
        name: "Cryolipolyse 2 zones",
        description: "",
        durée: "1h30",
        prix: 300,
      },
      {
        id: 4,
        name: "Cryolipolyse 3 zones",
        description: "",
        durée: "1h30",
        prix: 450,
      },
      {
        id: 5,
        name: "Cryolipolyse 4 zones",
        description: "",
        durée: "1h30",
        prix: 510,
      },
      {
        id: 6,
        name: "Pack cryolipolyse 1 zone - 3 séances",
        description: "Appeler le 07-50-20-58-44",
        durée: "",
        prix: 490,
      },
    ],
  },
  {
    id: 5,
    name: "EMS",
    description:
      "30 minutes d'EMS équivalent à 20000 abdos ou 20000 squats.\nPermet de développer les muscles et/ou brûler des graisses sans effort.\nStimulation électrique qui permet une contraction supra maximale du muscle qui n'est pas possible naturellement.\nTechnologie de pointe non invasive.\nTrès bon complément de la cryolipolyse.",
    photo: photo,
    prestations: [
      {
        id: 1,
        name: "Consultation",
        description:
          "Prenez obligatoirement un rendez-vous gratuit afin que je puisse répondre à toutes vos interrogations et/ou vous faire un devis.",
        durée: "30min",
        prix: 0,
      },
      {
        id: 2,
        name: "Cryolipolyse 1 zone",
        description: "",
        durée: "1h30",
        prix: 180,
      },
      {
        id: 3,
        name: "Cryolipolyse 2 zones",
        description: "",
        durée: "1h30",
        prix: 300,
      },
      {
        id: 4,
        name: "Cryolipolyse 3 zones",
        description: "",
        durée: "1h30",
        prix: 450,
      },
    ],
  },
]

export default soins
